version: '3.8' 

services:
  frontend:
    image: hamzakhalloufieg/frontend:latest  
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
